import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function seedExperiences() {
  console.log('🌱 Seeding experiences...')

  console.log('🧹 Clearing existing experience data...')
  await prisma.experienceReview.deleteMany()
  await prisma.experienceBooking.deleteMany()
  await prisma.experience.deleteMany()
  console.log('✅ Cleared previous experiences')

  // Get some hosts
  const hosts = await prisma.user.findMany({ 
    where: { isHost: true },
    take: 5 
  })

  if (hosts.length === 0) {
    console.log('⚠️  No hosts found. Using existing users as hosts...')
    const anyUsers = await prisma.user.findMany({ take: 1 })
    if (anyUsers.length > 0) {
      // Update existing user to be host
      const updatedHost = await prisma.user.update({
        where: { id: anyUsers[0].id },
        data: { isHost: true, role: 'HOST' },
      })
      hosts.push(updatedHost)
    } else {
      console.log('❌ No users found in database. Please seed users first.')
      return
    }
  }

  const experiencesData = [
    {
      hostId: hosts[0].id,
      title: 'Tour ẩm thực phố cổ Hà Nội',
      description: 'Khám phá hơn 10 món ăn đặc sản Hà Nội tại các quán ăn bản địa. Từ phở, bún chả đến chè, cafe trứng... Bạn sẽ được thưởng thức những món ăn ngon nhất và nghe câu chuyện về văn hóa ẩm thực Việt Nam.',
      category: 'FOOD_DRINK',
      city: 'Hà Nội',
      location: 'Quận Hoàn Kiếm, Hà Nội',
      latitude: 21.0285,
      longitude: 105.8542,
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
      images: [
        'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
        'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
      ],
      price: 450000,
      duration: '3 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 2,
      maxGuests: 8,
      includedItems: ['10+ món ăn', 'Hướng dẫn viên địa phương', 'Nước uống', 'Bảo hiểm'],
      notIncluded: ['Đưa đón', 'Tip cho hướng dẫn viên'],
      requirements: ['Không yêu cầu thể lực đặc biệt', 'Phù hợp mọi lứa tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Street food', 'Văn hóa', 'Walking tour'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.9,
      totalReviews: 187,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Lặn ngắm san hô Phú Quốc',
      description: 'Trải nghiệm lặn biển ngắm san hô tại các điểm đẹp nhất Phú Quốc. Thiết bị lặn chuyên nghiệp và hướng dẫn viên có chứng chỉ PADI. Phù hợp cho cả người mới bắt đầu.',
      category: 'WATER_SPORTS',
      city: 'Phú Quốc',
      state: 'Kiên Giang',
      location: 'Bãi Sao, Phú Quốc',
      latitude: 10.1699,
      longitude: 103.9653,
      image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
      images: [
        'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
        'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
      ],
      price: 850000,
      duration: '4 giờ',
      groupSize: 'Tối đa 6 người',
      minGuests: 1,
      maxGuests: 6,
      includedItems: ['Thiết bị lặn đầy đủ', 'Hướng dẫn viên PADI', 'Nước uống', 'Bảo hiểm', 'Đưa đón từ khách sạn'],
      notIncluded: ['Bữa trưa', 'Ảnh dưới nước (thuê thêm 200k)'],
      requirements: ['Biết bơi', 'Từ 12 tuổi trở lên', 'Khỏe mạnh'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Snorkeling', 'Biển đảo', 'Mạo hiểm', 'Thiên nhiên'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.8,
      totalReviews: 143,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Trekking & ngắm bình minh Fansipan',
      description: 'Leo núi Fansipan qua đêm, cắm trại và ngắm bình minh tuyệt đẹp trên đỉnh Đông Dương. Trải nghiệm đáng nhớ với thiên nhiên hùng vĩ của Sa Pa.',
      category: 'ADVENTURE',
      city: 'Sa Pa',
      state: 'Lào Cai',
      location: 'Fansipan, Sa Pa',
      latitude: 22.3019,
      longitude: 103.7750,
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      images: [
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
        'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
      ],
      price: 1200000,
      duration: '2 ngày 1 đêm',
      groupSize: 'Tối đa 10 người',
      minGuests: 2,
      maxGuests: 10,
      includedItems: ['Hướng dẫn viên chuyên nghiệp', 'Lều cắm trại', 'Túi ngủ', 'Bữa ăn (3 bữa)', 'Đèn pin', 'Bảo hiểm'],
      notIncluded: ['Giày leo núi (có thể thuê)', 'Quần áo ấm', 'Đồ dùng cá nhân'],
      requirements: ['Thể lực tốt', 'Từ 16 tuổi trở lên', 'Kinh nghiệm trekking cơ bản'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Trekking', 'Cắm trại', 'Núi non', 'Mạo hiểm', 'Bình minh'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.95,
      totalReviews: 89,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Học nấu món Việt truyền thống',
      description: 'Đi chợ truyền thống và học nấu 4 món Việt Nam cùng đầu bếp chuyên nghiệp. Thưởng thức bữa trưa do chính tay bạn nấu. Nhận công thức về nhà.',
      category: 'WORKSHOP',
      city: 'Hội An',
      state: 'Quảng Nam',
      location: 'Phố cổ Hội An',
      latitude: 15.8801,
      longitude: 108.3380,
      image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800',
      images: [
        'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800',
        'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800',
      ],
      price: 650000,
      duration: '4 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 1,
      maxGuests: 12,
      includedItems: ['Đi chợ cùng chef', 'Nguyên liệu nấu ăn', 'Dụng cụ nấu', 'Bữa trưa', 'Công thức món ăn', 'Nón lá & tạp dề'],
      notIncluded: ['Đưa đón', 'Đồ uống có cồn'],
      requirements: ['Không cần kinh nghiệm', 'Mọi lứa tuổi'],
      languages: ['Tiếng Việt', 'English', '中文'],
      tags: ['Cooking', 'Văn hóa', 'Ẩm thực', 'Workshop'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.7,
      totalReviews: 156,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Yoga & Meditation bên bờ biển',
      description: 'Buổi yoga và thiền buổi sáng trên bãi biển Đà Nẵng. Kết nối với thiên nhiên, tái tạo năng lượng và tìm thấy sự bình yên nội tâm.',
      category: 'WELLNESS',
      city: 'Đà Nẵng',
      location: 'Bãi biển Mỹ Khê',
      latitude: 16.0471,
      longitude: 108.2068,
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
      images: [
        'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
        'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
      ],
      price: 300000,
      duration: '90 phút',
      groupSize: 'Tối đa 15 người',
      minGuests: 1,
      maxGuests: 15,
      includedItems: ['Thảm yoga', 'Hướng dẫn viên chứng chỉ', 'Nước detox', 'Khăn lạnh'],
      notIncluded: ['Trang phục yoga', 'Bữa sáng'],
      requirements: ['Không cần kinh nghiệm', 'Mọi lứa tuổi', 'Mặc trang phục thoải mái'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Yoga', 'Thiền', 'Wellness', 'Biển', 'Sức khỏe'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.85,
      totalReviews: 92,
    },
    {
      hostId: hosts[0].id,
      title: 'Chèo thuyền kayak vịnh Hạ Long',
      description: 'Khám phá vẻ đẹp vịnh Hạ Long từ góc nhìn độc đáo trên thuyền kayak. Ghé thăm hang động, làng chài và những hòn đảo nhỏ xinh.',
      category: 'WATER_SPORTS',
      city: 'Hạ Long',
      state: 'Quảng Ninh',
      location: 'Vịnh Hạ Long',
      latitude: 20.9101,
      longitude: 107.1839,
      image: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800',
      images: [
        'https://images.unsplash.com/photo-1528127269322-539801943592?w=800',
      ],
      price: 550000,
      duration: '5 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 2,
      maxGuests: 8,
      includedItems: ['Thuyền kayak', 'Áo phao', 'Hướng dẫn viên', 'Bữa trưa', 'Nước uống', 'Bảo hiểm'],
      notIncluded: ['Đưa đón từ Hà Nội', 'Chi phí cá nhân'],
      requirements: ['Biết bơi cơ bản', 'Từ 10 tuổi trở lên', 'Khỏe mạnh'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Kayaking', 'Vịnh Hạ Long', 'Thiên nhiên', 'Phiêu lưu'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.75,
      totalReviews: 68,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Khám phá phố cổ Hà Nội bằng xích lô',
      description: 'Dạo quanh 36 phố phường bằng xích lô, nghe những câu chuyện thú vị về lịch sử và kiến trúc Hà Nội, dừng chân thưởng thức cà phê trứng và quà vặt.',
      category: 'SIGHTSEEING',
      city: 'Hà Nội',
      location: 'Phố cổ Hà Nội',
      latitude: 21.0330,
      longitude: 105.8500,
      image: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800',
      images: [
        'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800',
        'https://images.unsplash.com/photo-1503197979108-c824168d51a8?w=800',
      ],
      price: 320000,
      duration: '2 giờ',
      groupSize: 'Tối đa 6 người',
      minGuests: 1,
      maxGuests: 6,
      includedItems: ['Xe xích lô', 'Tài xế địa phương', 'Cà phê trứng', 'Nước suối'],
      notIncluded: ['Đưa đón khách sạn', 'Tip cho tài xế'],
      requirements: ['Mặc trang phục lịch sự', 'Đến trước 15 phút'],
      languages: ['Tiếng Việt', 'English', 'Français'],
      tags: ['City tour', 'Văn hóa', 'Lịch sử'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.82,
      totalReviews: 74,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Workshop làm lồng đèn Hội An',
      description: 'Học cách làm lồng đèn truyền thống cùng nghệ nhân Hội An, tự tay tạo nên chiếc lồng đèn độc đáo mang về làm kỷ niệm.',
      category: 'WORKSHOP',
      city: 'Hội An',
      state: 'Quảng Nam',
      location: 'Phường Minh An, Hội An',
      latitude: 15.8794,
      longitude: 108.3350,
      image: 'https://images.unsplash.com/photo-1526481280695-3c469ef2f576?w=800',
      images: [
        'https://images.unsplash.com/photo-1526481280695-3c469ef2f576?w=800',
        'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
      ],
      price: 280000,
      duration: '90 phút',
      groupSize: 'Tối đa 12 người',
      minGuests: 1,
      maxGuests: 12,
      includedItems: ['Nguyên liệu làm lồng đèn', 'Hướng dẫn viên', 'Trà thảo mộc', 'Bao bì mang về'],
      notIncluded: ['Đưa đón'],
      requirements: ['Phù hợp trẻ em từ 6 tuổi', 'Không cần kỹ năng thủ công'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Handmade', 'Văn hóa', 'Gia đình'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.93,
      totalReviews: 132,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Tour xe máy khám phá Sài Gòn về đêm',
      description: 'Ngồi sau xe máy cùng người dẫn đường bản địa, khám phá những con hẻm và địa điểm ăn uống nổi tiếng của Sài Gòn vào ban đêm.',
      category: 'NIGHTLIFE',
      city: 'Hồ Chí Minh',
      location: 'Quận 1, TP.HCM',
      latitude: 10.7769,
      longitude: 106.7009,
      image: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=800',
      images: [
        'https://images.unsplash.com/photo-1544441893-675973e31985?w=800',
        'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800',
      ],
      price: 650000,
      duration: '4 giờ',
      groupSize: 'Tối đa 10 người',
      minGuests: 1,
      maxGuests: 10,
      includedItems: ['Xe máy & nón bảo hiểm', '4 món ăn đường phố', 'Hướng dẫn viên', 'Bảo hiểm'],
      notIncluded: ['Đồ uống có cồn', 'Tip cho tài xế'],
      requirements: ['Không yêu cầu kỹ năng lái', 'Không say xe'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Street food', 'Nightlife', 'Adventure'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.88,
      totalReviews: 201,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Ngắm hoàng hôn trên sông Thu Bồn',
      description: 'Thả mình trên chiếc thuyền gỗ truyền thống, ngắm nhìn hoàng hôn phủ lên phố cổ Hội An, thả hoa đăng cầu bình an.',
      category: 'SIGHTSEEING',
      city: 'Hội An',
      state: 'Quảng Nam',
      location: 'Sông Thu Bồn',
      latitude: 15.8779,
      longitude: 108.3273,
      image: 'https://images.unsplash.com/photo-1582277264836-030231c20386?w=800',
      images: [
        'https://images.unsplash.com/photo-1582277264836-030231c20386?w=800',
        'https://images.unsplash.com/photo-1580137185505-357553730b54?w=800',
      ],
      price: 350000,
      duration: '75 phút',
      groupSize: 'Tối đa 6 người',
      minGuests: 2,
      maxGuests: 6,
      includedItems: ['Thuyền gỗ', 'Người chèo thuyền', 'Hoa đăng', 'Trà thảo mộc'],
      notIncluded: ['Đưa đón'],
      requirements: ['Phù hợp mọi lứa tuổi', 'Không mang giày cao gót'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Sunset', 'Trải nghiệm lãng mạn', 'Văn hóa'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.86,
      totalReviews: 98,
    },
    {
      hostId: hosts[0].id,
      title: 'Tour kiến trúc thuộc địa Sài Gòn',
      description: 'Khám phá nhà thờ Đức Bà, Bưu điện trung tâm và những công trình kiến trúc Pháp cổ kính cùng hướng dẫn viên lịch sử.',
      category: 'CULTURE',
      city: 'Hồ Chí Minh',
      location: 'Quận 1, TP.HCM',
      latitude: 10.7798,
      longitude: 106.6990,
      image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
      images: [
        'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        'https://images.unsplash.com/photo-1572515071159-79b4c053b83b?w=800',
      ],
      price: 400000,
      duration: '3 giờ',
      groupSize: 'Tối đa 15 người',
      minGuests: 1,
      maxGuests: 15,
      includedItems: ['Hướng dẫn viên lịch sử', 'Vé tham quan', 'Tai nghe thuyết minh'],
      notIncluded: ['Đưa đón', 'Đồ uống'],
      requirements: ['Mặc trang phục lịch sự', 'Mang theo mũ nón'],
      languages: ['Tiếng Việt', 'English', '日本語'],
      tags: ['History', 'Architecture', 'Walking tour'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.74,
      totalReviews: 121,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Tham quan hầm rượu vang Đà Lạt',
      description: 'Khám phá hầm ủ vang trăm tuổi, tìm hiểu quy trình làm vang Đà Lạt và thưởng thức 5 loại vang cùng phô mai địa phương.',
      category: 'FOOD_DRINK',
      city: 'Đà Lạt',
      state: 'Lâm Đồng',
      location: 'Hầm rượu vang Ladofoods',
      latitude: 11.9404,
      longitude: 108.4583,
      image: 'https://images.unsplash.com/photo-1515308242703-83bb61edc1a9?w=800',
      images: [
        'https://images.unsplash.com/photo-1515308242703-83bb61edc1a9?w=800',
        'https://images.unsplash.com/photo-1543062094-1b52dbdf84d8?w=800',
      ],
      price: 480000,
      duration: '2 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Vé tham quan', 'Hướng dẫn viên sommeliers', '5 loại vang', 'Phô mai địa phương'],
      notIncluded: ['Đưa đón'],
      requirements: ['Trên 18 tuổi', 'Không mang trẻ em'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Wine tasting', 'Ẩm thực', 'Đà Lạt'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.69,
      totalReviews: 54,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Chèo SUP ngắm bình minh Hồ Tây',
      description: 'Trải nghiệm chèo SUP trên mặt nước tĩnh lặng của Hồ Tây lúc bình minh, học kỹ thuật cơ bản và chụp ảnh check-in tuyệt đẹp.',
      category: 'WATER_SPORTS',
      city: 'Hà Nội',
      location: 'Hồ Tây',
      latitude: 21.0570,
      longitude: 105.8229,
      image: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800',
      images: [
        'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800',
        'https://images.unsplash.com/photo-1564767609342-620cb19b2357?w=800',
      ],
      price: 520000,
      duration: '2 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 1,
      maxGuests: 8,
      includedItems: ['Ván SUP', 'Áo phao', 'Hướng dẫn viên', 'Ảnh chụp'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không sợ nước', 'Biết bơi cơ bản'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['SUP', 'Bình minh', 'Thể thao'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.91,
      totalReviews: 67,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Tour chợ nổi Cái Răng và vườn trái cây',
      description: 'Đón bình minh trên chợ nổi Cái Răng, thưởng thức bún riêu trên ghe, khám phá vườn trái cây Nam Bộ và trải nghiệm làm bánh tét.',
      category: 'CULTURE',
      city: 'Cần Thơ',
      location: 'Chợ nổi Cái Răng',
      latitude: 9.9786,
      longitude: 105.7690,
      image: 'https://images.unsplash.com/photo-1528164344705-47542687000d?w=800',
      images: [
        'https://images.unsplash.com/photo-1528164344705-47542687000d?w=800',
        'https://images.unsplash.com/photo-1524492449096-2e8c0a0d3ff2?w=800',
      ],
      price: 780000,
      duration: '6 giờ',
      groupSize: 'Tối đa 14 người',
      minGuests: 2,
      maxGuests: 14,
      includedItems: ['Tàu gỗ', 'Ăn sáng trên chợ nổi', 'Vé tham quan vườn trái cây', 'Lớp làm bánh tét', 'Nước uống'],
      notIncluded: ['Đưa đón từ TP.HCM'],
      requirements: ['Khởi hành 5:00 sáng', 'Mang nón, kem chống nắng'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Chợ nổi', 'Văn hóa miền Tây', 'Ẩm thực'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.9,
      totalReviews: 112,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Săn mây đồi chè Cầu Đất',
      description: 'Thức dậy lúc bình minh, di chuyển lên đồi chè Cầu Đất săn mây và thưởng thức bữa sáng picnic giữa biển mây Đà Lạt.',
      category: 'ADVENTURE',
      city: 'Đà Lạt',
      state: 'Lâm Đồng',
      location: 'Đồi chè Cầu Đất',
      latitude: 11.8787,
      longitude: 108.5445,
      image: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800',
      images: [
        'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800',
        'https://images.unsplash.com/photo-1512295767273-ac109ac3acfa?w=800',
      ],
      price: 590000,
      duration: '5 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Xe jeep đưa đón', 'Ăn sáng picnic', 'Hướng dẫn viên', 'Ảnh chụp'],
      notIncluded: ['Áo ấm', 'Găng tay'],
      requirements: ['Dậy sớm 4:00 sáng', 'Mang áo ấm'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Săn mây', 'Đà Lạt', 'Nhiếp ảnh'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.92,
      totalReviews: 134,
    },
    {
      hostId: hosts[0].id,
      title: 'Lớp học cà phê specialty Sài Gòn',
      description: 'Tìm hiểu về hạt cà phê Việt Nam, trải nghiệm rang, xay và pha espresso/aeropress cùng barista chuyên nghiệp.',
      category: 'WORKSHOP',
      city: 'Hồ Chí Minh',
      location: 'Quận Bình Thạnh, TP.HCM',
      latitude: 10.8050,
      longitude: 106.7142,
      image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
      images: [
        'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
        'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
      ],
      price: 420000,
      duration: '3 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 1,
      maxGuests: 8,
      includedItems: ['Hạt cà phê Arabica/Robusta', 'Dụng cụ pha', 'Giáo trình', 'Đồ uống miễn phí'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không mang trẻ em dưới 10 tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Coffee', 'Workshop', 'Specialty'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.87,
      totalReviews: 76,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Tour chụp ảnh chuyên nghiệp phố cổ Hội An',
      description: 'Tham gia cùng nhiếp ảnh gia địa phương để ghi lại những khoảnh khắc đẹp nhất tại Hội An. Bao gồm make-up nhẹ và 60 ảnh chỉnh sửa.',
      category: 'ENTERTAINMENT',
      city: 'Hội An',
      state: 'Quảng Nam',
      location: 'Phố cổ Hội An',
      latitude: 15.8783,
      longitude: 108.3287,
      image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
      images: [
        'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        'https://images.unsplash.com/photo-1540202404-1a52317e1d87?w=800',
      ],
      price: 890000,
      duration: '3 giờ',
      groupSize: 'Tối đa 4 người',
      minGuests: 1,
      maxGuests: 4,
      includedItems: ['Nhiếp ảnh gia chuyên nghiệp', 'Make-up nhẹ', '60 ảnh chỉnh màu', 'Trang phục áo dài (tùy chọn)'],
      notIncluded: ['Đưa đón'],
      requirements: ['Thông báo trước size trang phục'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Photography', 'Hội An', 'Couple'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.94,
      totalReviews: 83,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Đạp xe xuyên rừng dừa Bảy Mẫu',
      description: 'Đạp xe qua những con đường làng quê, tham gia chèo thuyền thúng tại rừng dừa Bảy Mẫu và thưởng thức bữa trưa dân dã.',
      category: 'ADVENTURE',
      city: 'Hội An',
      state: 'Quảng Nam',
      location: 'Xã Cẩm Thanh',
      latitude: 15.8790,
      longitude: 108.3720,
      image: 'https://images.unsplash.com/photo-1529516543985-307b4eff265a?w=800',
      images: [
        'https://images.unsplash.com/photo-1529516543985-307b4eff265a?w=800',
        'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800',
      ],
      price: 510000,
      duration: '5 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Xe đạp', 'Thuyền thúng', 'Bữa trưa', 'Hướng dẫn viên'],
      notIncluded: ['Đưa đón từ Đà Nẵng'],
      requirements: ['Biết đi xe đạp', 'Mang nón, kem chống nắng'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Cycling', 'Sinh thái', 'Trải nghiệm địa phương'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.83,
      totalReviews: 91,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Workshop làm gốm Bát Tràng',
      description: 'Tham gia lớp học làm gốm truyền thống, tự tay nặn và trang trí sản phẩm, tìm hiểu lịch sử làng nghề Bát Tràng.',
      category: 'WORKSHOP',
      city: 'Hà Nội',
      location: 'Làng gốm Bát Tràng',
      latitude: 20.9738,
      longitude: 105.9138,
      image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800',
      images: [
        'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800',
        'https://images.unsplash.com/photo-1514977104531-9eee19a49b54?w=800',
      ],
      price: 260000,
      duration: '2 giờ',
      groupSize: 'Tối đa 15 người',
      minGuests: 1,
      maxGuests: 15,
      includedItems: ['Đất sét', 'Bàn xoay', 'Lò nung (nhận sau 3 ngày)', 'Hướng dẫn viên', 'Nước uống thảo mộc'],
      notIncluded: ['Vận chuyển sản phẩm về nhà'],
      requirements: ['Nên mặc quần áo dễ giặt', 'Phù hợp trẻ em >=5 tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Handicraft', 'Culture', 'Family friendly'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.79,
      totalReviews: 65,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Tour xe jeep khám phá bán đảo Sơn Trà',
      description: 'Ngồi xe jeep cổ điển băng qua rừng Sơn Trà, ghé thăm chùa Linh Ứng, cây đa nghìn năm và ngắm thành phố Đà Nẵng từ trên cao.',
      category: 'ADVENTURE',
      city: 'Đà Nẵng',
      location: 'Bán đảo Sơn Trà',
      latitude: 16.1165,
      longitude: 108.2700,
      image: 'https://images.unsplash.com/photo-1512036849132-895b1bc54143?w=800',
      images: [
        'https://images.unsplash.com/photo-1512036849132-895b1bc54143?w=800',
        'https://images.unsplash.com/photo-1523968060458-21cb515103d3?w=800',
      ],
      price: 950000,
      duration: '4 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 2,
      maxGuests: 8,
      includedItems: ['Xe jeep cổ điển', 'Tài xế kiêm hướng dẫn', 'Nước suối & khăn lạnh', 'Ảnh chụp bằng máy film'],
      notIncluded: ['Vé vào chùa'],
      requirements: ['Không say xe', 'Không phù hợp phụ nữ mang thai'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Jeep tour', 'Nature', 'Photography'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.9,
      totalReviews: 102,
    },
    {
      hostId: hosts[0].id,
      title: 'Ẩm thực đường phố Hà Nội về đêm',
      description: 'Thưởng thức 8 món đường phố đặc trưng như phở áp chảo, nem chua rán, bia hơi... cùng food blogger nổi tiếng.',
      category: 'FOOD_DRINK',
      city: 'Hà Nội',
      location: 'Quận Hoàn Kiếm',
      latitude: 21.0338,
      longitude: 105.8361,
      image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800',
      images: [
        'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800',
        'https://images.unsplash.com/photo-1608032367062-1fb61b56474b?w=800',
      ],
      price: 490000,
      duration: '3 giờ',
      groupSize: 'Tối đa 10 người',
      minGuests: 1,
      maxGuests: 10,
      includedItems: ['8 món ăn', '2 đồ uống', 'Hướng dẫn viên kiêm food blogger', 'Ảnh chụp'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không dị ứng hải sản', 'Mang giày thoải mái'],
      languages: ['Tiếng Việt', 'English', '한국어'],
      tags: ['Food tour', 'Nightlife', 'Street food'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.95,
      totalReviews: 210,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Trải nghiệm farmstay và làm nông Đà Lạt',
      description: 'Một ngày làm nông dân tại trang trại hữu cơ, thu hoạch rau củ, học chế biến salad và đồ uống healthy.',
      category: 'WELLNESS',
      city: 'Đà Lạt',
      state: 'Lâm Đồng',
      location: 'Xã Xuân Thọ, Đà Lạt',
      latitude: 11.9490,
      longitude: 108.4990,
      image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800',
      images: [
        'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800',
        'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800',
      ],
      price: 550000,
      duration: '6 giờ',
      groupSize: 'Tối đa 20 người',
      minGuests: 4,
      maxGuests: 20,
      includedItems: ['Hướng dẫn viên nông trại', 'Dụng cụ làm vườn', 'Ăn trưa healthy', 'Workshop làm kombucha'],
      notIncluded: ['Đưa đón'],
      requirements: ['Mang giày thể thao', 'Không dị ứng phấn hoa'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Farmstay', 'Wellness', 'Family'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.7,
      totalReviews: 58,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Tour khám phá hầm Củ Chi',
      description: 'Trải nghiệm hệ thống địa đạo Củ Chi, bắn súng thử thách và thưởng thức khoai mì nướng truyền thống.',
      category: 'CULTURE',
      city: 'Hồ Chí Minh',
      location: 'Huyện Củ Chi',
      latitude: 11.0567,
      longitude: 106.5014,
      image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800',
      images: [
        'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800',
        'https://images.unsplash.com/photo-1529429617124-aee0a8d13f7d?w=800',
      ],
      price: 780000,
      duration: '7 giờ',
      groupSize: 'Tối đa 20 người',
      minGuests: 4,
      maxGuests: 20,
      includedItems: ['Xe đưa đón', 'Vé tham quan', 'Hướng dẫn viên lịch sử', 'Ăn nhẹ khoai mì'],
      notIncluded: ['Phí bắn súng thử', 'Bữa trưa'],
      requirements: ['Không sợ không gian hẹp'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['History', 'Culture', 'War relic'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.76,
      totalReviews: 187,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Lớp dạy làm bánh mì Việt',
      description: 'Học bí quyết làm bánh mì thịt nướng giòn rụm cùng đầu bếp chuyên nghiệp, từ khâu làm pate đến nước sốt đặc biệt.',
      category: 'WORKSHOP',
      city: 'Hồ Chí Minh',
      location: 'Quận 3, TP.HCM',
      latitude: 10.7837,
      longitude: 106.6881,
      image: 'https://images.unsplash.com/photo-1576400889893-959fe3c62097?w=800',
      images: [
        'https://images.unsplash.com/photo-1576400889893-959fe3c62097?w=800',
        'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800',
      ],
      price: 430000,
      duration: '3 giờ',
      groupSize: 'Tối đa 10 người',
      minGuests: 1,
      maxGuests: 10,
      includedItems: ['Nguyên liệu tươi', 'Dụng cụ bếp', 'Công thức chi tiết', 'Đồ uống lạnh'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không dị ứng gluten'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Cooking class', 'Bánh mì', 'Foodie'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.89,
      totalReviews: 72,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Tour trekking bản Cát Cát và thác Tình Yêu',
      description: 'Hành trình trekking xuyên bản làng dân tộc H’Mông, ghé thăm thác Tình Yêu và trải nghiệm dệt vải lanh truyền thống.',
      category: 'ADVENTURE',
      city: 'Sa Pa',
      state: 'Lào Cai',
      location: 'Bản Cát Cát',
      latitude: 22.3120,
      longitude: 103.8300,
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
      images: [
        'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
        'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
      ],
      price: 540000,
      duration: '6 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Hướng dẫn viên địa phương', 'Vé tham quan', 'Ăn trưa', 'Áo mưa dùng một lần'],
      notIncluded: ['Xe từ thị trấn đến điểm bắt đầu'],
      requirements: ['Thể lực trung bình', 'Mang giày trekking'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Trekking', 'Ethnic culture', 'Waterfall'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.84,
      totalReviews: 109,
    },
    {
      hostId: hosts[0].id,
      title: 'Khóa học pha chế cocktail signature Sài Gòn',
      description: 'Học cách pha chế 4 loại cocktail hiện đại sử dụng nguyên liệu Việt Nam như sả, lá dứa, rượu nếp cùng bartender đạt giải quốc tế.',
      category: 'WORKSHOP',
      city: 'Hồ Chí Minh',
      location: 'Quận 1, TP.HCM',
      latitude: 10.7763,
      longitude: 106.7005,
      image: 'https://images.unsplash.com/photo-1514361892635-6e122620e748?w=800',
      images: [
        'https://images.unsplash.com/photo-1514361892635-6e122620e748?w=800',
        'https://images.unsplash.com/photo-1563371351-e53ebb744a1b?w=800',
      ],
      price: 650000,
      duration: '3 giờ',
      groupSize: 'Tối đa 10 người',
      minGuests: 1,
      maxGuests: 10,
      includedItems: ['Nguyên liệu pha chế', '4 công thức độc quyền', 'Đồ uống miễn phí', 'Chứng nhận hoàn thành'],
      notIncluded: ['Đồ ăn nhẹ'],
      requirements: ['Trên 18 tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Mixology', 'Nightlife', 'Workshop'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.78,
      totalReviews: 52,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Khám phá hang động Phong Nha',
      description: 'Thám hiểm hệ thống hang động kỳ vĩ tại Phong Nha - Kẻ Bàng, chèo thuyền trên sông Son và trekking trong lòng hang ướt.',
      category: 'ADVENTURE',
      city: 'Đồng Hới',
      state: 'Quảng Bình',
      location: 'Phong Nha - Kẻ Bàng',
      latitude: 17.5343,
      longitude: 106.2813,
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
      images: [
        'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
        'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800',
      ],
      price: 1450000,
      duration: '1 ngày',
      groupSize: 'Tối đa 14 người',
      minGuests: 4,
      maxGuests: 14,
      includedItems: ['Xe đưa đón Đồng Hới', 'Vé tham quan', 'Ăn trưa picnic', 'Thiết bị an toàn', 'Hướng dẫn viên chuyên nghiệp'],
      notIncluded: ['Bảo hiểm du lịch nâng cao'],
      requirements: ['Thể lực tốt', 'Không sợ tối', 'Không phù hợp trẻ em dưới 8 tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Cave exploration', 'Adventure', 'UNESCO'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.97,
      totalReviews: 145,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Thư giãn spa bùn khoáng Nha Trang',
      description: 'Ngâm bùn khoáng nóng, massage đá biển và thưởng thức trà thảo mộc tại khu spa cao cấp nằm trên đồi nhìn ra biển.',
      category: 'WELLNESS',
      city: 'Nha Trang',
      state: 'Khánh Hòa',
      location: 'Khu du lịch Trăm Trứng',
      latitude: 12.1746,
      longitude: 109.1590,
      image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
      images: [
        'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        'https://images.unsplash.com/photo-1535448041621-0f18118268aa?w=800',
      ],
      price: 620000,
      duration: '2 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 1,
      maxGuests: 8,
      includedItems: ['Vé spa bùn khoáng', 'Massage đá biển 30 phút', 'Trà thảo mộc và trái cây', 'Khăn tắm & locker'],
      notIncluded: ['Đưa đón khách sạn'],
      requirements: ['Không phù hợp phụ nữ mang thai 3 tháng đầu'],
      languages: ['Tiếng Việt', 'English', 'Русский'],
      tags: ['Spa', 'Wellness', 'Relax'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.73,
      totalReviews: 88,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Tour du thuyền hạng sang vịnh Nha Trang',
      description: 'Thưởng ngoạn cảnh biển trên du thuyền sang trọng, snorkeling tại hòn Mun và thưởng thức tiệc hải sản tươi sống.',
      category: 'WATER_SPORTS',
      city: 'Nha Trang',
      state: 'Khánh Hòa',
      location: 'Vịnh Nha Trang',
      latitude: 12.2388,
      longitude: 109.1967,
      image: 'https://images.unsplash.com/photo-1527289630990-1fc2d1e68908?w=800',
      images: [
        'https://images.unsplash.com/photo-1527289630990-1fc2d1e68908?w=800',
        'https://images.unsplash.com/photo-1521207418485-99c705420785?w=800',
      ],
      price: 1850000,
      duration: '6 giờ',
      groupSize: 'Tối đa 20 người',
      minGuests: 6,
      maxGuests: 20,
      includedItems: ['Du thuyền hạng sang', 'Thiết bị snorkeling', 'Tiệc hải sản buffet', 'DJ & âm nhạc', 'Bảo hiểm'],
      notIncluded: ['Đồ uống có cồn cao cấp'],
      requirements: ['Đặt trước 3 ngày', 'Không mang giày cao gót'],
      languages: ['Tiếng Việt', 'English', '中文'],
      tags: ['Yacht', 'Luxury', 'Water sports'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.88,
      totalReviews: 63,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Chợ đêm Đà Lạt & nhạc acoustic',
      description: 'Thưởng thức không khí se lạnh của Đà Lạt, thưởng thức khoai nướng, sữa đậu nành nóng và nghe nhạc acoustic bên hồ Xuân Hương.',
      category: 'ENTERTAINMENT',
      city: 'Đà Lạt',
      state: 'Lâm Đồng',
      location: 'Chợ đêm Đà Lạt',
      latitude: 11.9465,
      longitude: 108.4419,
      image: 'https://images.unsplash.com/photo-1492171998980-b10faff82045?w=800',
      images: [
        'https://images.unsplash.com/photo-1492171998980-b10faff82045?w=800',
        'https://images.unsplash.com/photo-1528150177507-200de3c5a37f?w=800',
      ],
      price: 280000,
      duration: '3 giờ',
      groupSize: 'Tối đa 15 người',
      minGuests: 2,
      maxGuests: 15,
      includedItems: ['Hướng dẫn viên địa phương', '2 món ăn đường phố', 'Chỗ ngồi nhạc acoustic', 'Nước nóng'],
      notIncluded: ['Đưa đón'],
      requirements: ['Mang áo ấm', 'Phù hợp mọi lứa tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Night market', 'Music', 'Local food'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.65,
      totalReviews: 41,
    },
    {
      hostId: hosts[0].id,
      title: 'Tour street art và cafe ẩn mình Hà Nội',
      description: 'Khám phá các bức tranh tường street art mới nổi, ghé thăm những quán cafe ẩn mình trong biệt thự Pháp cổ và nghe câu chuyện nghệ sĩ.',
      category: 'CULTURE',
      city: 'Hà Nội',
      location: 'Quận Hai Bà Trưng và Ba Đình',
      latitude: 21.0270,
      longitude: 105.8340,
      image: 'https://images.unsplash.com/photo-1542539097-86406c6b8488?w=800',
      images: [
        'https://images.unsplash.com/photo-1542539097-86406c6b8488?w=800',
        'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800',
      ],
      price: 370000,
      duration: '3 giờ',
      groupSize: 'Tối đa 10 người',
      minGuests: 1,
      maxGuests: 10,
      includedItems: ['Hướng dẫn viên nghệ thuật', '2 đồ uống đặc sản', 'Vé triển lãm', 'Ảnh Polaroid'],
      notIncluded: ['Đưa đón'],
      requirements: ['Mang giày thoải mái'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Art tour', 'Café culture', 'Creative'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.81,
      totalReviews: 57,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Thưởng trà đạo Việt - Nhật kết hợp',
      description: 'Trải nghiệm trà đạo độc đáo kết hợp giữa nghệ thuật trà Việt và Nhật, học cách pha và thưởng thức 4 loại trà đặc biệt.',
      category: 'WELLNESS',
      city: 'Hà Nội',
      location: 'Quận Tây Hồ',
      latitude: 21.0712,
      longitude: 105.8185,
      image: 'https://images.unsplash.com/photo-1507914372361-5de5ca8182e8?w=800',
      images: [
        'https://images.unsplash.com/photo-1507914372361-5de5ca8182e8?w=800',
        'https://images.unsplash.com/photo-1545033078-7e56019a2171?w=800',
      ],
      price: 360000,
      duration: '2 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 1,
      maxGuests: 8,
      includedItems: ['4 loại trà thủ công', 'Bánh wagashi Việt', 'Không gian trà thất', 'Tài liệu trà đạo'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không dùng nước hoa đậm mùi'],
      languages: ['Tiếng Việt', 'English', '日本語'],
      tags: ['Tea ceremony', 'Zen', 'Culture'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.77,
      totalReviews: 39,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Tour câu mực đêm Phú Quốc',
      description: 'Ra khơi trên thuyền gỗ truyền thống, học kỹ thuật câu mực và thưởng thức thành quả ngay trên tàu với cháo mực nóng.',
      category: 'WATER_SPORTS',
      city: 'Phú Quốc',
      state: 'Kiên Giang',
      location: 'Cảng Dương Đông',
      latitude: 10.2296,
      longitude: 103.9607,
      image: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=800',
      images: [
        'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=800',
        'https://images.unsplash.com/photo-1526498460520-4c246339dccb?w=800',
      ],
      price: 430000,
      duration: '4 giờ',
      groupSize: 'Tối đa 15 người',
      minGuests: 4,
      maxGuests: 15,
      includedItems: ['Thuyền đánh mực', 'Dụng cụ câu', 'Cháo mực', 'Bảo hiểm', 'Hướng dẫn viên'],
      notIncluded: ['Đưa đón khách sạn'],
      requirements: ['Không say sóng nặng'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Night fishing', 'Seafood', 'Adventure'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.66,
      totalReviews: 58,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Khảo sát làng chài Rạch Vẹm & sao biển',
      description: 'Khám phá làng chài Rạch Vẹm hoang sơ, chụp ảnh cùng sao biển và thưởng thức bữa trưa hải sản tại nhà dân.',
      category: 'SIGHTSEEING',
      city: 'Phú Quốc',
      state: 'Kiên Giang',
      location: 'Làng chài Rạch Vẹm',
      latitude: 10.3190,
      longitude: 103.9070,
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
      images: [
        'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
        'https://images.unsplash.com/photo-1520565373696-21d4e5a54c75?w=800',
      ],
      price: 620000,
      duration: '5 giờ',
      groupSize: 'Tối đa 16 người',
      minGuests: 4,
      maxGuests: 16,
      includedItems: ['Xe đưa đón', 'Thuyền gỗ', 'Bữa trưa hải sản', 'Nước dừa'],
      notIncluded: ['Đồ uống có cồn'],
      requirements: ['Mang đồ bơi', 'Không bắt sao biển ra khỏi nước lâu'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Island life', 'Seafood', 'Photography'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.8,
      totalReviews: 46,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Ngắm hoàng hôn Grandworld & show Tinh hoa Việt Nam',
      description: 'Dạo bước trên Venice thu nhỏ tại Grandworld, ngắm hoàng hôn trên kênh và thưởng thức show Tinh hoa Việt Nam hoành tráng.',
      category: 'ENTERTAINMENT',
      city: 'Phú Quốc',
      state: 'Kiên Giang',
      location: 'Grandworld Phú Quốc',
      latitude: 10.3760,
      longitude: 103.8610,
      image: 'https://images.unsplash.com/photo-1503264116251-35a269479413?w=800',
      images: [
        'https://images.unsplash.com/photo-1503264116251-35a269479413?w=800',
        'https://images.unsplash.com/photo-1526481280695-3c469ef2f576?w=800',
      ],
      price: 760000,
      duration: '4 giờ',
      groupSize: 'Tối đa 20 người',
      minGuests: 4,
      maxGuests: 20,
      includedItems: ['Vé vào cổng', 'Vé show Tinh hoa Việt Nam', 'Hướng dẫn viên', 'Nước suối'],
      notIncluded: ['Bữa tối'],
      requirements: ['Đặt trước 24h'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Show diễn', 'Nightlife', 'Culture'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.7,
      totalReviews: 37,
    },
    {
      hostId: hosts[0].id,
      title: 'Tour chụp ảnh cưới phong cách vintage Hà Nội',
      description: 'Gói chụp ảnh cưới 3 giờ với studio nổi tiếng, makeup chuyên nghiệp và di chuyển bằng xe con bọ cổ điển quanh Hà Nội.',
      category: 'ENTERTAINMENT',
      city: 'Hà Nội',
      location: 'Phố cổ & Hồ Gươm',
      latitude: 21.0288,
      longitude: 105.8524,
      image: 'https://images.unsplash.com/photo-1520853504280-249b72dc9470?w=800',
      images: [
        'https://images.unsplash.com/photo-1520853504280-249b72dc9470?w=800',
        'https://images.unsplash.com/photo-1519741497674-611481863552?w=800',
      ],
      price: 6500000,
      duration: '3 giờ',
      groupSize: 'Tối đa 2 người',
      minGuests: 1,
      maxGuests: 2,
      includedItems: ['Makeup artist', 'Nhiếp ảnh gia', 'Xe con bọ cổ', '70 ảnh chỉnh màu', '2 ảnh in canvas'],
      notIncluded: ['Trang phục cưới'],
      requirements: ['Đặt cọc 50%', 'Thông báo concept trước 3 ngày'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Wedding', 'Photography', 'Vintage'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.96,
      totalReviews: 29,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Workshop làm sô cô la Bean-to-bar',
      description: 'Từ hạt cacao Trị An đến thanh sô cô la hoàn thiện, học kỹ thuật rang, xay, tempering và tạo hình chocolate thủ công.',
      category: 'WORKSHOP',
      city: 'Hồ Chí Minh',
      location: 'Quận 2, TP.HCM',
      latitude: 10.7800,
      longitude: 106.7465,
      image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
      images: [
        'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
        'https://images.unsplash.com/photo-1523475472560-d2df97ec485c?w=800',
      ],
      price: 720000,
      duration: '4 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 2,
      maxGuests: 8,
      includedItems: ['Hạt cacao tươi', 'Dụng cụ làm chocolate', 'Tạp dề', '3 sản phẩm mang về'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không dị ứng cacao'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Chocolate', 'DIY', 'Foodie'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.85,
      totalReviews: 44,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Khám phá chợ đêm Bến Thành và lớp mặc cả',
      description: 'Tìm hiểu lịch sử chợ Bến Thành, học kỹ năng trả giá và thưởng thức món bánh tráng nướng nổi tiếng.',
      category: 'SHOPPING',
      city: 'Hồ Chí Minh',
      location: 'Chợ Bến Thành',
      latitude: 10.7723,
      longitude: 106.6984,
      image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
      images: [
        'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
        'https://images.unsplash.com/photo-1530554764233-e79e16c91d08?w=800',
      ],
      price: 250000,
      duration: '2 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Hướng dẫn viên địa phương', 'Checklist mua sắm', '1 món ăn đường phố', 'Nước suối'],
      notIncluded: ['Chi phí mua sắm'],
      requirements: ['Mang tiền mặt', 'Mặc trang phục gọn nhẹ'],
      languages: ['Tiếng Việt', 'English', '中文'],
      tags: ['Market tour', 'Shopping', 'Street food'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.68,
      totalReviews: 62,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Trải nghiệm phố đi bộ Bùi Viện VIP',
      description: 'Khám phá nightlife Sài Gòn với bàn VIP trên rooftop, cocktail signature và hướng dẫn viên nightlife nhiệt tình.',
      category: 'NIGHTLIFE',
      city: 'Hồ Chí Minh',
      location: 'Phố đi bộ Bùi Viện',
      latitude: 10.7689,
      longitude: 106.6935,
      image: 'https://images.unsplash.com/photo-1523528821156-6b73f4256f42?w=800',
      images: [
        'https://images.unsplash.com/photo-1523528821156-6b73f4256f42?w=800',
        'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800',
      ],
      price: 990000,
      duration: '4 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Bàn VIP rooftop', '2 cocktail signature', 'Snack', 'Hướng dẫn viên nightlife'],
      notIncluded: ['Đồ uống thêm'],
      requirements: ['Trên 18 tuổi', 'Trang phục smart casual'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Nightlife', 'Rooftop', 'Party'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.75,
      totalReviews: 51,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Lớp học pha trà sữa thủ công',
      description: 'Tự tay làm trân châu, pha 3 công thức trà sữa signature và học cách thiết kế menu đồ uống cho quán nhỏ.',
      category: 'WORKSHOP',
      city: 'Hồ Chí Minh',
      location: 'Quận Phú Nhuận',
      latitude: 10.8011,
      longitude: 106.6800,
      image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=800',
      images: [
        'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=800',
        'https://images.unsplash.com/photo-1527169402691-feff5539e52c?w=800',
      ],
      price: 360000,
      duration: '3 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Nguyên liệu pha chế', 'Tài liệu công thức', 'Bao bì mang về', 'Đồ uống miễn phí'],
      notIncluded: ['Đưa đón'],
      requirements: ['Đặt trước 2 ngày'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Bubble tea', 'DIY', 'Workshop'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.72,
      totalReviews: 47,
    },
    {
      hostId: hosts[0].id,
      title: 'Chèo thuyền SUP ngắm rừng tràm Trà Sư',
      description: 'Lướt trên mặt nước xanh biếc giữa rừng tràm mùa nước nổi, ngắm đàn chim và thưởng thức bánh canh cá linh.',
      category: 'ADVENTURE',
      city: 'An Giang',
      location: 'Rừng tràm Trà Sư',
      latitude: 10.5465,
      longitude: 105.0826,
      image: 'https://images.unsplash.com/photo-1572274407049-3b71afca3a2e?w=800',
      images: [
        'https://images.unsplash.com/photo-1572274407049-3b71afca3a2e?w=800',
        'https://images.unsplash.com/photo-1526481280695-3c469ef2f576?w=800',
      ],
      price: 590000,
      duration: '5 giờ',
      groupSize: 'Tối đa 10 người',
      minGuests: 4,
      maxGuests: 10,
      includedItems: ['Vé vào cổng', 'Thuyền tắc ráng', 'SUP', 'Ăn trưa', 'Bảo hiểm'],
      notIncluded: ['Đưa đón từ TP.HCM'],
      requirements: ['Không sợ nước', 'Biết bơi cơ bản'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Nature', 'Birdwatching', 'SUP'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.82,
      totalReviews: 43,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Khám phá nhà thờ gỗ Kon Tum & làng Kon Klor',
      description: 'Học về kiến trúc nhà thờ gỗ trăm tuổi, tham gia dệt thổ cẩm và thưởng thức rượu cần cùng nghệ nhân Ba Na.',
      category: 'CULTURE',
      city: 'Kon Tum',
      location: 'Nhà thờ gỗ Kon Tum',
      latitude: 14.3500,
      longitude: 108.0000,
      image: 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=800',
      images: [
        'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=800',
        'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800',
      ],
      price: 720000,
      duration: '7 giờ',
      groupSize: 'Tối đa 15 người',
      minGuests: 4,
      maxGuests: 15,
      includedItems: ['Xe đưa đón', 'Vé tham quan', 'Hướng dẫn viên', 'Bữa trưa đặc sản'],
      notIncluded: ['Chi phí mua đặc sản'],
      requirements: ['Tôn trọng văn hóa địa phương'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Ethnic culture', 'Architecture', 'Heritage'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.79,
      totalReviews: 31,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Tour săn dãy ngân hà tại bán đảo Sơn Trà',
      description: 'Đêm ngắm sao và chụp ảnh milky way cùng nhiếp ảnh gia thiên văn, học kỹ thuật phơi sáng dài và chỉnh màu cơ bản.',
      category: 'ENTERTAINMENT',
      city: 'Đà Nẵng',
      location: 'Đỉnh Bàn Cờ',
      latitude: 16.1240,
      longitude: 108.2705,
      image: 'https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?w=800',
      images: [
        'https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?w=800',
        'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=800',
      ],
      price: 780000,
      duration: '5 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 2,
      maxGuests: 8,
      includedItems: ['Xe đưa đón', 'Tripod', 'Hướng dẫn chụp ảnh', 'Cacao nóng'],
      notIncluded: ['Máy ảnh cá nhân'],
      requirements: ['Mang áo ấm', 'Không sợ cao'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Astrophotography', 'Night activity', 'Adventure'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.93,
      totalReviews: 34,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Điêu khắc gỗ mỹ nghệ Đồng Kỵ',
      description: 'Làm quen với kỹ thuật chạm khắc gỗ truyền thống, tự tay khắc hoa văn cơ bản và tham quan xưởng đồ gỗ cao cấp.',
      category: 'WORKSHOP',
      city: 'Bắc Ninh',
      location: 'Làng nghề Đồng Kỵ',
      latitude: 21.1230,
      longitude: 105.9770,
      image: 'https://images.unsplash.com/photo-1523419409543-0c1df022bdd7?w=800',
      images: [
        'https://images.unsplash.com/photo-1523419409543-0c1df022bdd7?w=800',
        'https://images.unsplash.com/photo-1505576391880-95a31c08c065?w=800',
      ],
      price: 540000,
      duration: '4 giờ',
      groupSize: 'Tối đa 10 người',
      minGuests: 2,
      maxGuests: 10,
      includedItems: ['Gỗ nguyên liệu', 'Dụng cụ chạm khắc', 'Bữa trưa nhẹ', 'Sản phẩm mang về'],
      notIncluded: ['Đưa đón từ Hà Nội'],
      requirements: ['Mang găng tay', 'Không phù hợp trẻ em dưới 10 tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Handicraft', 'Woodwork', 'Culture'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.71,
      totalReviews: 25,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Trải nghiệm thu hoạch cà phê Tây Nguyên',
      description: 'Tham gia cùng nông dân thu hái, phơi và rang cà phê Robusta/Ethiopia tại Buôn Ma Thuột, thưởng thức cà phê chồn.',
      category: 'FOOD_DRINK',
      city: 'Buôn Ma Thuột',
      location: 'Buôn Đôn',
      latitude: 12.6833,
      longitude: 108.0500,
      image: 'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800',
      images: [
        'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800',
        'https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=800',
      ],
      price: 640000,
      duration: '7 giờ',
      groupSize: 'Tối đa 15 người',
      minGuests: 4,
      maxGuests: 15,
      includedItems: ['Xe di chuyển', 'Bữa trưa đặc sản', 'Workshop rang xay', '3 túi cà phê mang về'],
      notIncluded: ['Chi phí vận chuyển cà phê thêm'],
      requirements: ['Mang nón và kem chống nắng'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Coffee farm', 'Agriculture', 'Culture'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.87,
      totalReviews: 48,
    },
    {
      hostId: hosts[0].id,
      title: 'Kayak xuyên hang Luồn Hạ Long',
      description: 'Chèo kayak vào hang Luồn, ngắm đàn voọc đầu trắng quý hiếm và thưởng thức bữa trưa hải sản trên tàu.',
      category: 'WATER_SPORTS',
      city: 'Hạ Long',
      state: 'Quảng Ninh',
      location: 'Hang Luồn',
      latitude: 20.9250,
      longitude: 107.0650,
      image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800',
      images: [
        'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800',
        'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800',
      ],
      price: 730000,
      duration: '6 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 4,
      maxGuests: 12,
      includedItems: ['Xe đưa đón từ bến Tuần Châu', 'Kayak', 'Áo phao', 'Bữa trưa hải sản', 'Bảo hiểm'],
      notIncluded: ['Đưa đón từ Hà Nội'],
      requirements: ['Biết bơi', 'Không sợ nước sâu'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Kayak', 'Nature', 'Wildlife'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.89,
      totalReviews: 77,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Workshop nước mắm thủ công Phú Quốc',
      description: 'Tham quan nhà thùng nước mắm truyền thống, học quy trình ủ cá cơm và pha chế nước chấm ngon chuẩn vị Nam Bộ.',
      category: 'FOOD_DRINK',
      city: 'Phú Quốc',
      state: 'Kiên Giang',
      location: 'Nhà thùng Khải Hoàn',
      latitude: 10.2290,
      longitude: 103.9510,
      image: 'https://images.unsplash.com/photo-1559304887-98f7fb8fa569?w=800',
      images: [
        'https://images.unsplash.com/photo-1559304887-98f7fb8fa569?w=800',
        'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?w=800',
      ],
      price: 340000,
      duration: '2 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Hướng dẫn viên nhà thùng', 'Thử nếm 3 loại nước mắm', 'Công thức pha nước chấm', 'Set quà tặng 250ml'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không phù hợp người dị ứng hải sản'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Fish sauce', 'Traditional craft', 'Food culture'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.74,
      totalReviews: 33,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Tour đường hầm Điện Biên Phủ ảo thực tế',
      description: 'Ứng dụng VR tái hiện chiến dịch Điện Biên Phủ, kết hợp thăm bảo tàng và hầm De Castries cùng nhà nghiên cứu lịch sử.',
      category: 'CULTURE',
      city: 'Điện Biên Phủ',
      state: 'Điện Biên',
      location: 'Chiến trường Điện Biên Phủ',
      latitude: 21.3860,
      longitude: 103.0213,
      image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
      images: [
        'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
        'https://images.unsplash.com/photo-1544377193-33dcf4d68fb5?w=800',
      ],
      price: 680000,
      duration: '5 giờ',
      groupSize: 'Tối đa 18 người',
      minGuests: 6,
      maxGuests: 18,
      includedItems: ['Hướng dẫn viên lịch sử', 'Thiết bị VR', 'Vé bảo tàng', 'Ăn trưa nhẹ'],
      notIncluded: ['Vé máy bay'],
      requirements: ['Không bị say VR', 'Tôn trọng di tích'],
      languages: ['Tiếng Việt', 'English', 'Français'],
      tags: ['History', 'VR', 'Educational'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.83,
      totalReviews: 28,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Khám phá vườn quốc gia Cát Tiên bằng xe đạp',
      description: 'Đạp xe xuyên rừng nguyên sinh, quan sát động vật hoang dã và tham gia hoạt động tắm rừng Shinrin Yoku.',
      category: 'ADVENTURE',
      city: 'Đồng Nai',
      location: 'Vườn quốc gia Cát Tiên',
      latitude: 11.4285,
      longitude: 107.4256,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
      images: [
        'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
        'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?w=800',
      ],
      price: 870000,
      duration: '1 ngày',
      groupSize: 'Tối đa 12 người',
      minGuests: 4,
      maxGuests: 12,
      includedItems: ['Xe đạp địa hình', 'Hướng dẫn viên sinh học', 'Ăn trưa picnic', 'Bảo hiểm'],
      notIncluded: ['Đưa đón từ TP.HCM'],
      requirements: ['Thể lực tốt', 'Không phù hợp trẻ dưới 8 tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Cycling', 'Ecotourism', 'Wildlife'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.9,
      totalReviews: 52,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Show thực cảnh Ký ức Hội An VIP',
      description: 'Trải nghiệm show diễn thực cảnh lớn nhất Việt Nam với ghế VIP, hậu trường backstage và gặp gỡ diễn viên.',
      category: 'ENTERTAINMENT',
      city: 'Hội An',
      state: 'Quảng Nam',
      location: 'Đảo Ký Ức Hội An',
      latitude: 15.8730,
      longitude: 108.3340,
      image: 'https://images.unsplash.com/photo-1512916206820-41ea78aca60a?w=800',
      images: [
        'https://images.unsplash.com/photo-1512916206820-41ea78aca60a?w=800',
        'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
      ],
      price: 1250000,
      duration: '3 giờ',
      groupSize: 'Tối đa 20 người',
      minGuests: 4,
      maxGuests: 20,
      includedItems: ['Vé VIP', 'Tour hậu trường', 'Nước uống welcome', 'Quà lưu niệm'],
      notIncluded: ['Đưa đón'],
      requirements: ['Đặt trước 48h'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Show diễn', 'Culture', 'Nightlife'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.92,
      totalReviews: 88,
    },
    {
      hostId: hosts[0].id,
      title: 'Lớp vẽ tranh sơn mài truyền thống',
      description: 'Tìm hiểu kỹ thuật sơn mài Hạ Thái, thực hành vẽ họa tiết và hoàn thiện tác phẩm nhỏ mang về.',
      category: 'WORKSHOP',
      city: 'Hà Nội',
      location: 'Làng nghề Hạ Thái',
      latitude: 20.8772,
      longitude: 105.7415,
      image: 'https://images.unsplash.com/photo-1529101091764-c3526daf38fe?w=800',
      images: [
        'https://images.unsplash.com/photo-1529101091764-c3526daf38fe?w=800',
        'https://images.unsplash.com/photo-1523413651479-597eb2da0ad6?w=800',
      ],
      price: 580000,
      duration: '4 giờ',
      groupSize: 'Tối đa 10 người',
      minGuests: 2,
      maxGuests: 10,
      includedItems: ['Vật liệu sơn mài', 'Giáo trình', 'Bữa trưa nhẹ', 'Tác phẩm mang về'],
      notIncluded: ['Đưa đón từ trung tâm'],
      requirements: ['Không mặc đồ trắng'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Art workshop', 'Handicraft', 'Culture'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.76,
      totalReviews: 42,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Trải nghiệm homestay người Dao đỏ Tả Phìn',
      description: 'Ở lại nhà người Dao đỏ, tắm lá thuốc cổ truyền và học thêu hoa văn truyền thống.',
      category: 'CULTURE',
      city: 'Sa Pa',
      state: 'Lào Cai',
      location: 'Bản Tả Phìn',
      latitude: 22.3535,
      longitude: 103.8847,
      image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800',
      images: [
        'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800',
        'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
      ],
      price: 980000,
      duration: '2 ngày 1 đêm',
      groupSize: 'Tối đa 10 người',
      minGuests: 2,
      maxGuests: 10,
      includedItems: ['Chỗ ở homestay', '3 bữa ăn', 'Tắm lá thuốc', 'Workshop thêu'],
      notIncluded: ['Xe từ thị trấn Sa Pa'],
      requirements: ['Tôn trọng phong tục địa phương'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Homestay', 'Ethnic culture', 'Wellness'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.94,
      totalReviews: 66,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Tour tàu hỏa răng cưa Đà Lạt – Trại Mát',
      description: 'Lên tàu hỏa cổ răng cưa, tham quan chùa Linh Phước và trải nghiệm làm mứt hoa quả tại Trại Mát.',
      category: 'SIGHTSEEING',
      city: 'Đà Lạt',
      state: 'Lâm Đồng',
      location: 'Ga Đà Lạt',
      latitude: 11.9469,
      longitude: 108.4527,
      image: 'https://images.unsplash.com/photo-1519810765831-21b0097b0785?w=800',
      images: [
        'https://images.unsplash.com/photo-1519810765831-21b0097b0785?w=800',
        'https://images.unsplash.com/photo-1517638851339-4aa32003c11a?w=800',
      ],
      price: 460000,
      duration: '3 giờ',
      groupSize: 'Tối đa 20 người',
      minGuests: 4,
      maxGuests: 20,
      includedItems: ['Vé tàu hỏa khứ hồi', 'Hướng dẫn viên', 'Workshop làm mứt', 'Nước ấm'],
      notIncluded: ['Đưa đón'],
      requirements: ['Đến trước 30 phút'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Train ride', 'Culture', 'Family'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.68,
      totalReviews: 59,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Khóa học nhiếp ảnh đường phố Sài Gòn',
      description: 'Cùng nhiếp ảnh gia báo chí ghi lại nhịp sống Sài Gòn, học kỹ thuật chụp candid và kể chuyện bằng ảnh.',
      category: 'WORKSHOP',
      city: 'Hồ Chí Minh',
      location: 'Quận 5, Chợ Lớn',
      latitude: 10.7540,
      longitude: 106.6630,
      image: 'https://images.unsplash.com/photo-1526476148966-99ad2fc76d1d?w=800',
      images: [
        'https://images.unsplash.com/photo-1526476148966-99ad2fc76d1d?w=800',
        'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800',
      ],
      price: 520000,
      duration: '4 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 1,
      maxGuests: 8,
      includedItems: ['Hướng dẫn nhiếp ảnh', 'Review portfolio', 'Bản đồ spot chụp', 'Nước uống'],
      notIncluded: ['Máy ảnh cá nhân'],
      requirements: ['Biết sử dụng máy ảnh cơ bản'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Photography', 'Street life', 'Workshop'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.82,
      totalReviews: 53,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Thử thách canyoning thác Datanla',
      description: 'Rappelling xuống vách đá 25m, trượt nước và nhảy tự do tại thác Datanla cùng đội ngũ cứu hộ chuyên nghiệp.',
      category: 'ADVENTURE',
      city: 'Đà Lạt',
      state: 'Lâm Đồng',
      location: 'Thác Datanla',
      latitude: 11.9121,
      longitude: 108.4551,
      image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800',
      images: [
        'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800',
        'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
      ],
      price: 1380000,
      duration: '6 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 4,
      maxGuests: 12,
      includedItems: ['Thiết bị bảo hộ', 'Hướng dẫn viên chuyên nghiệp', 'Ăn trưa picnic', 'Bảo hiểm'],
      notIncluded: ['Đưa đón'],
      requirements: ['Thể lực tốt', 'Không sợ độ cao'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Canyoning', 'Adventure', 'Waterfall'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.95,
      totalReviews: 71,
    },
    {
      hostId: hosts[0].id,
      title: 'Tour ẩm thực chay cao cấp Hà Nội',
      description: 'Thưởng thức thực đơn chay 7 món tại nhà hàng Michelin Bib Gourmand và học triết lý ẩm thực chay Việt.',
      category: 'FOOD_DRINK',
      city: 'Hà Nội',
      location: 'Quận Tây Hồ',
      latitude: 21.0580,
      longitude: 105.8210,
      image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800',
      images: [
        'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800',
        'https://images.unsplash.com/photo-1493770348161-369560ae357d?w=800',
      ],
      price: 880000,
      duration: '3 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 2,
      maxGuests: 8,
      includedItems: ['Thực đơn chay 7 món', 'Trà hoa sen', 'Buổi trò chuyện với bếp trưởng', 'Sách công thức'],
      notIncluded: ['Đưa đón'],
      requirements: ['Thông báo dị ứng trước'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Fine dining', 'Vegan', 'Culture'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.9,
      totalReviews: 32,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Bí mật cocktail thảo mộc Hội An',
      description: 'Khám phá quầy bar speakeasy, học cách pha cocktail thảo mộc với rượu gạo và gia vị địa phương.',
      category: 'NIGHTLIFE',
      city: 'Hội An',
      state: 'Quảng Nam',
      location: 'Speakeasy Trà Quế',
      latitude: 15.8935,
      longitude: 108.3450,
      image: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?w=800',
      images: [
        'https://images.unsplash.com/photo-1497534446932-c925b458314e?w=800',
        'https://images.unsplash.com/photo-1580715904863-af49e0cc0490?w=800',
      ],
      price: 610000,
      duration: '2 giờ',
      groupSize: 'Tối đa 10 người',
      minGuests: 2,
      maxGuests: 10,
      includedItems: ['3 cocktail signature', 'Set tapas', 'Công thức', 'Quà lưu niệm'],
      notIncluded: ['Đưa đón'],
      requirements: ['Trên 18 tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Cocktail', 'Nightlife', 'Mixology'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.84,
      totalReviews: 36,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Tour Vespa cổ khám phá Huế',
      description: 'Cưỡi Vespa cổ thăm Đại Nội, lăng Tự Đức và thưởng trà sen trên sông Hương.',
      category: 'SIGHTSEEING',
      city: 'Huế',
      location: 'Kinh thành Huế',
      latitude: 16.4710,
      longitude: 107.5750,
      image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800',
      images: [
        'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800',
        'https://images.unsplash.com/photo-1475938476802-32a7e851dad1?w=800',
      ],
      price: 990000,
      duration: '5 giờ',
      groupSize: 'Tối đa 8 người',
      minGuests: 2,
      maxGuests: 8,
      includedItems: ['Vespa cổ + tài xế', 'Vé tham quan', 'Ăn trưa món Huế', 'Trà sen'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không say xe'],
      languages: ['Tiếng Việt', 'English', 'Français'],
      tags: ['Heritage', 'Vintage', 'Sightseeing'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.91,
      totalReviews: 55,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Khóa học làm nước mắm chay Kombu',
      description: 'Sáng tạo nước mắm chay từ tảo kombu và nấm shiitake, phù hợp người ăn chay và vegan.',
      category: 'WORKSHOP',
      city: 'Hà Nội',
      location: 'Quận Đống Đa',
      latitude: 21.0160,
      longitude: 105.8300,
      image: 'https://images.unsplash.com/photo-1514516345957-556ca7d90a19?w=800',
      images: [
        'https://images.unsplash.com/photo-1514516345957-556ca7d90a19?w=800',
        'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
      ],
      price: 320000,
      duration: '2 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Nguyên liệu hữu cơ', 'Lọ thủy tinh', 'Công thức PDF', 'Đồ uống thảo mộc'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không dị ứng nấm biển'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Vegan', 'DIY', 'Workshop'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.7,
      totalReviews: 22,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Tour cà phê trứng & jazz Hà Nội',
      description: 'Nghe jazz sống tại bar cổ điển, thưởng thức cà phê trứng cùng mixologist sáng tạo nước uống lấy cảm hứng từ âm nhạc.',
      category: 'ENTERTAINMENT',
      city: 'Hà Nội',
      location: 'Quận Hoàn Kiếm',
      latitude: 21.0305,
      longitude: 105.8520,
      image: 'https://images.unsplash.com/photo-1527169402691-feff5539e52c?w=800',
      images: [
        'https://images.unsplash.com/photo-1527169402691-feff5539e52c?w=800',
        'https://images.unsplash.com/photo-1523365280197-f1783db9fe62?w=800',
      ],
      price: 490000,
      duration: '2 giờ',
      groupSize: 'Tối đa 20 người',
      minGuests: 2,
      maxGuests: 20,
      includedItems: ['Vé nghe jazz', 'Cà phê trứng', '1 cocktail signature', 'Gặp gỡ ban nhạc'],
      notIncluded: ['Đưa đón'],
      requirements: ['Trang phục smart casual'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Live music', 'Coffee culture', 'Nightlife'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.88,
      totalReviews: 38,
    },
    {
      hostId: hosts[0].id,
      title: 'Khám phá phố Nhật Bản Đà Nẵng',
      description: 'Trải nghiệm văn hóa Nhật tại Đà Nẵng, học trà đạo, mặc yukata và thưởng thức ẩm thực fusion Việt - Nhật.',
      category: 'CULTURE',
      city: 'Đà Nẵng',
      location: 'Phố Nhật Bản An Thượng',
      latitude: 16.0492,
      longitude: 108.2420,
      image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800',
      images: [
        'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800',
        'https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=800',
      ],
      price: 610000,
      duration: '3 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Workshop trà đạo', 'Thuê yukata', 'Bữa tối fusion', 'Ảnh chụp'],
      notIncluded: ['Đưa đón'],
      requirements: ['Đặt trước 3 ngày để chuẩn bị yukata'],
      languages: ['Tiếng Việt', 'English', '日本語'],
      tags: ['Culture fusion', 'Tea ceremony', 'Foodie'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.75,
      totalReviews: 27,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Tour nghệ thuật đương đại TP.HCM',
      description: 'Tham quan gallery, studio nghệ sĩ trẻ và tham gia workshop nghệ thuật tương tác tại Quận 2.',
      category: 'CULTURE',
      city: 'Hồ Chí Minh',
      location: 'Thảo Điền, TP.HCM',
      latitude: 10.8090,
      longitude: 106.7350,
      image: 'https://images.unsplash.com/photo-1526498460520-4c246339dccb?w=800',
      images: [
        'https://images.unsplash.com/photo-1526498460520-4c246339dccb?w=800',
        'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?w=800',
      ],
      price: 520000,
      duration: '4 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Vé gallery', 'Workshop tương tác', 'Đồ uống thủ công', 'Gặp gỡ nghệ sĩ'],
      notIncluded: ['Đưa đón'],
      requirements: ['Trang phục lịch sự'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Art tour', 'Gallery', 'Creative'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.8,
      totalReviews: 35,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Trải nghiệm cấy lúa ở Tam Cốc',
      description: 'Mặc áo tứ thân, xuống đồng cấy lúa cùng nông dân Ninh Bình và chèo đò trên sông Ngô Đồng.',
      category: 'CULTURE',
      city: 'Ninh Bình',
      location: 'Tam Cốc – Bích Động',
      latitude: 20.2500,
      longitude: 105.9400,
      image: 'https://images.unsplash.com/photo-1533636721434-0e2d61030955?w=800',
      images: [
        'https://images.unsplash.com/photo-1533636721434-0e2d61030955?w=800',
        'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
      ],
      price: 750000,
      duration: '1 ngày',
      groupSize: 'Tối đa 18 người',
      minGuests: 4,
      maxGuests: 18,
      includedItems: ['Xe đưa đón Hà Nội', 'Trang phục truyền thống', 'Ăn trưa', 'Đò Tam Cốc'],
      notIncluded: ['Chi phí mua đặc sản'],
      requirements: ['Mang đồ dễ giặt'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Countryside', 'Culture', 'Hands-on'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.9,
      totalReviews: 61,
    },
    {
      hostId: hosts[3]?.id || hosts[0].id,
      title: 'Thử sức DJ cơ bản tại Sài Gòn',
      description: 'Workshop DJ 1-1 với producer, học mix basic, beatmatching và tạo playlist cho buổi tiệc.',
      category: 'ENTERTAINMENT',
      city: 'Hồ Chí Minh',
      location: 'Quận 10, TP.HCM',
      latitude: 10.7720,
      longitude: 106.6670,
      image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
      images: [
        'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
        'https://images.unsplash.com/photo-1464375117522-1311d6a5b81a?w=800',
      ],
      price: 690000,
      duration: '2 giờ',
      groupSize: 'Tối đa 4 người',
      minGuests: 1,
      maxGuests: 4,
      includedItems: ['Thiết bị DJ Pioneer', 'Instructor 1-1', 'Đồ uống mềm', 'Video recap'],
      notIncluded: ['Đưa đón'],
      requirements: ['Trên 16 tuổi'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['DJ', 'Music', 'Nightlife'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.73,
      totalReviews: 26,
    },
    {
      hostId: hosts[4]?.id || hosts[0].id,
      title: 'Yoga trên bãi cát trắng Phú Yên',
      description: 'Buổi yoga bình minh trên bãi Xép, thiền biển và ăn sáng healthy với hải sản tươi.',
      category: 'WELLNESS',
      city: 'Tuy Hòa',
      state: 'Phú Yên',
      location: 'Bãi Xép',
      latitude: 13.0840,
      longitude: 109.2820,
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
      images: [
        'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
        'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
      ],
      price: 380000,
      duration: '3 giờ',
      groupSize: 'Tối đa 15 người',
      minGuests: 2,
      maxGuests: 15,
      includedItems: ['Thảm yoga', 'Huấn luyện viên', 'Ăn sáng healthy', 'Ảnh chụp drone'],
      notIncluded: ['Đưa đón'],
      requirements: ['Không cần kinh nghiệm'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Yoga', 'Beach', 'Wellness'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.86,
      totalReviews: 33,
    },
    {
      hostId: hosts[0].id,
      title: 'Tour trekking Tà Xùa săn mây',
      description: 'Leo núi Tà Xùa, ngủ lều trên đỉnh và săn mây biển cả với hướng dẫn viên bản địa.',
      category: 'ADVENTURE',
      city: 'Sơn La',
      location: 'Đỉnh Tà Xùa',
      latitude: 21.2950,
      longitude: 104.2910,
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
      images: [
        'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
        'https://images.unsplash.com/photo-1523419409543-0c1df022bdd7?w=800',
      ],
      price: 1680000,
      duration: '3 ngày 2 đêm',
      groupSize: 'Tối đa 12 người',
      minGuests: 4,
      maxGuests: 12,
      includedItems: ['Xe đưa đón Hà Nội', 'Lều trại', 'Ăn uống đầy đủ', 'Hướng dẫn viên', 'Bảo hiểm'],
      notIncluded: ['Thuê gậy trekking'],
      requirements: ['Thể lực tốt', 'Không phù hợp trẻ em'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Trekking', 'Camping', 'Cloud hunting'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.96,
      totalReviews: 58,
    },
    {
      hostId: hosts[1]?.id || hosts[0].id,
      title: 'Khám phá Vườn quốc gia Phú Quý bằng xe máy điện',
      description: 'Vi vu bằng xe máy điện quanh đảo Phú Quý, check-in cột mốc chủ quyền và lặn ngắm rạn san hô.',
      category: 'ADVENTURE',
      city: 'Phú Quý',
      state: 'Bình Thuận',
      location: 'Đảo Phú Quý',
      latitude: 10.5167,
      longitude: 108.9500,
      image: 'https://images.unsplash.com/photo-1529516543985-307b4eff265a?w=800',
      images: [
        'https://images.unsplash.com/photo-1529516543985-307b4eff265a?w=800',
        'https://images.unsplash.com/photo-1527289630990-1fc2d1e68908?w=800',
      ],
      price: 980000,
      duration: '1 ngày',
      groupSize: 'Tối đa 10 người',
      minGuests: 4,
      maxGuests: 10,
      includedItems: ['Xe máy điện', 'Hướng dẫn viên', 'Ăn trưa hải sản', 'Thiết bị snorkeling'],
      notIncluded: ['Vé tàu cao tốc'],
      requirements: ['Có bằng lái A1', 'Không say sóng'],
      languages: ['Tiếng Việt', 'English'],
      tags: ['Island tour', 'Eco travel', 'Water sports'],
      status: 'ACTIVE',
      isVerified: true,
      featured: false,
      averageRating: 4.85,
      totalReviews: 30,
    },
    {
      hostId: hosts[2]?.id || hosts[0].id,
      title: 'Thưởng thức opera tại Nhà hát Lớn Hà Nội',
      description: 'Vé hạng A xem opera, tour hậu trường gặp nghệ sĩ và tiệc cocktail trước giờ diễn.',
      category: 'ENTERTAINMENT',
      city: 'Hà Nội',
      location: 'Nhà hát Lớn Hà Nội',
      latitude: 21.0245,
      longitude: 105.8575,
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
      images: [
        'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
        'https://images.unsplash.com/photo-1533237267605-a4a0cccb4d9c?w=800',
      ],
      price: 1450000,
      duration: '3 giờ',
      groupSize: 'Tối đa 12 người',
      minGuests: 2,
      maxGuests: 12,
      includedItems: ['Vé hạng A', 'Cocktail', 'Tour hậu trường', 'Ảnh chụp chuyên nghiệp'],
      notIncluded: ['Đưa đón'],
      requirements: ['Trang phục formal'],
      languages: ['Tiếng Việt', 'English', 'Français'],
      tags: ['Opera', 'Culture', 'Luxury'],
      status: 'ACTIVE',
      isVerified: true,
      featured: true,
      averageRating: 4.93,
      totalReviews: 41,
    },
  ]

  for (const expData of experiencesData) {
    await prisma.experience.create({
      data: expData,
    })
  }

  console.log(`✅ Created ${experiencesData.length} experiences`)
}

seedExperiences()
  .catch((e) => {
    console.error('Error seeding experiences:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
